### ISSUE TITLE
Debug Client without the server

### ISSUE THREAD

**Issue by RicoSaupeB** [Dzoukr/SAFEr.Template#15]
I am running a separate backend and have the need to only run and debug the client. How would be the settings for VS Code or JB Rider?

**Comment by Dzoukr** [comment]
You can change the `build.fs` file to don't run server at all (just comment out the server part), or create a new target in the same file and run it `dotnet run myNewAwesomeTarget`

**Comment by RicoSaupeB** [comment]
Yes, I removed the server part already and the client is starting. No problems with that. But I need to get the debugger of VSCode or Rider attached. 

![image](https://user-images.githubusercontent.com/83805528/229498336-96615dbf-04b8-4e9e-a30d-6945ef7b911b.png)

![image](https://user-images.githubusercontent.com/83805528/229498685-491ec7cf-cc51-468e-ac7a-02e004a700c5.png)

**Comment by Dzoukr** [comment]
Shouldn't be too much different from the official documentation, I suppose:

https://safe-stack.github.io/docs/recipes/developing-and-testing/debug-safe-app/

**Comment by RicoSaupeB** [comment]
It works like described for SAFE. There I can debug the client with the F12 tools. I can see the webpack folder with the fs file and create breakpoints. 
![image](https://user-images.githubusercontent.com/83805528/234816895-0eef5388-c3c7-4c38-a9c4-f70795075d51.png)

For SAFEr I cannot see the webpack node in the tools and dont see and fs files. 

![image](https://user-images.githubusercontent.com/83805528/234816655-b488ff3e-eae4-4c86-9ba0-d2f3466a80f1.png)

Any suggestions on what I am doing wrong? If it works with F12 tools can it also work with VSCode?

**Comment by Dzoukr** [comment]
This template is not using Webpack anymore (it's based on vite.js - https://vitejs.dev/), so maybe it's coming from this?

**Comment by RicoSaupeB** [comment]
I see. I haven't found any way to debug using Vite in F12 or VScode. Apprecciate any input there.

**Comment by RicoSaupeB** [comment]
Has anyone solved that problem?

**Comment by MangelMaxime** [comment]
In order to debug F# instead of JavaScript, you need to have source maps just like in JavaScript/TypeScript.

When using Fable, you can enable source map generation using `--sourceMaps` flag. See `dotnet fable help` for all the options availables.

In my project running `dotnet fable watch --sourceMaps` is all that is needed to have F# code debuggable in the browser.


https://github.com/Dzoukr/SAFEr.Template/assets/4760796/735fdfad-22c5-4403-91bd-083c8022268e

**Comment by RicoSaupeB** [comment]
Thanks Maxime. That I was missing. Thanks for the great help.
